# Settings.yml
---
conf.py:
  ##==========================================
  ## define configuration data for conf.py as
  ## "parameter: value" pairs here:
  ##------------------------------------------
  exampleParameter: example value
  copyright: 2015
  project: Welcome!
  version: 1.0
  release: 1.0.0
  intersphinx_mapping:
    t3api:
    - https://docs.typo3.org/typo3cms/CoreApiReference
    - null
    t3cgl:
    - https://docs.typo3.org/typo3cms/CodingGuidelinesReference
    - null
    t3editors:
    - https://docs.typo3.org/typo3cms/EditorsTutorial
    - null
    t3extbase:
    - https://docs.typo3.org/typo3cms/ExtbaseGuide
    - null
    t3extbasebook:
    - https://docs.typo3.org/typo3cms/ExtbaseFluidBook
    - null
    t3fal:
    - https://docs.typo3.org/typo3cms/FileAbstractionLayerReference
    - null
    t3inside:
    - https://docs.typo3.org/typo3cms/InsideTypo3Reference
    - null
    t3install:
    - https://docs.typo3.org/typo3cms/InstallationGuide
    - null
    t3l10n:
    - https://docs.typo3.org/typo3cms/FrontendLocalizationGuide
    - null
    t3security:
    - https://docs.typo3.org/typo3cms/SecurityGuide
    - null
    t3services:
    - https://docs.typo3.org/typo3cms/Typo3ServicesReference
    - null
    t3skinning:
    - https://docs.typo3.org/typo3cms/SkinningReference
    - null
    t3start:
    - https://docs.typo3.org/typo3cms/GettingStartedTutorial
    - null
    t3tca:
    - https://docs.typo3.org/typo3cms/TCAReference
    - null
    t3templating:
    - https://docs.typo3.org/typo3cms/TemplatingTutorial
    - null
    t3ts45:
    - https://docs.typo3.org/typo3cms/TyposcriptIn45MinutesTutorial
    - null
    t3tsconfig:
    - https://docs.typo3.org/typo3cms/TSconfigReference
    - null
    t3tsref:
    - https://docs.typo3.org/typo3cms/TyposcriptReference
    - null
    t3tssyntax:
    - https://docs.typo3.org/typo3cms/TyposcriptSyntaxReference
    - null

...
